In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv(r"C:\Users\sridhar rathod\Downloads\archive (4)\Amazon_Best_Seller.csv")

In [ ]:
df

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
346,Winter of the World: Book Two of the Century T...,Ken Follett,4.5,10760,15,2012,Fiction
347,Women Food and God: An Unexpected Path to Almo...,Geneen Roth,4.2,1302,11,2010,Non Fiction
348,Wonder,R. J. Palacio,4.8,21625,9,2013,Fiction
349,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
350,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         351 non-null    str
 1   Author       351 non-null    str
 2   User Rating  351 non-null    float64
 3   Reviews      351 non-null    int64
 4   Price        351 non-null    int64
 5   Year         351 non-null    int64
 6   Genre        351 non-null    str
dtypes: float64(1), int64(3), str(3)
memory usage: 44.4 KB

In [ ]:
df.dropna()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
346,Winter of the World: Book Two of the Century T...,Ken Follett,4.5,10760,15,2012,Fiction
347,Women Food and God: An Unexpected Path to Almo...,Geneen Roth,4.2,1302,11,2010,Non Fiction
348,Wonder,R. J. Palacio,4.8,21625,9,2013,Fiction
349,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
350,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction

In [ ]:
df.drop_duplicates()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
346,Winter of the World: Book Two of the Century T...,Ken Follett,4.5,10760,15,2012,Fiction
347,Women Food and God: An Unexpected Path to Almo...,Geneen Roth,4.2,1302,11,2010,Non Fiction
348,Wonder,R. J. Palacio,4.8,21625,9,2013,Fiction
349,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
350,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction

In [ ]:
df.describe()

       User Rating       Reviews       Price        Year
count   351.000000    351.000000  351.000000   351.00000
mean      4.608832   9799.683761   13.076923  2013.51567
std       0.226669  10871.356548   10.050860     3.28271
min       3.300000     37.000000    0.000000  2009.00000
25%       4.500000   3442.500000    8.000000  2010.00000
50%       4.600000   6346.000000   12.000000  2013.00000
75%       4.800000  11470.500000   16.000000  2016.00000
max       4.900000  87841.000000  105.000000  2019.00000

In [ ]:
df.sum()

Name           10-Day Green Smoothie Cleanse11/22/63: A Novel...
Author         JJ SmithStephen KingJordan B. PetersonGeorge O...
User Rating                                               1617.7
Reviews                                                  3439689
Price                                                       4590
Year                                                      706744
Genre          Non FictionFictionNon FictionFictionNon Fictio...
dtype: object

In [ ]:
df.isnull()

      Name  Author  User Rating  Reviews  Price   Year  Genre
0    False   False        False    False  False  False  False
1    False   False        False    False  False  False  False
2    False   False        False    False  False  False  False
3    False   False        False    False  False  False  False
4    False   False        False    False  False  False  False
..     ...     ...          ...      ...    ...    ...    ...
346  False   False        False    False  False  False  False
347  False   False        False    False  False  False  False
348  False   False        False    False  False  False  False
349  False   False        False    False  False  False  False
350  False   False        False    False  False  False  False

[351 rows x 7 columns]

In [ ]:
df.isnull().head(10)

    Name  Author  User Rating  Reviews  Price   Year  Genre
0  False   False        False    False  False  False  False
1  False   False        False    False  False  False  False
2  False   False        False    False  False  False  False
3  False   False        False    False  False  False  False
4  False   False        False    False  False  False  False
5  False   False        False    False  False  False  False
6  False   False        False    False  False  False  False
7  False   False        False    False  False  False  False
8  False   False        False    False  False  False  False
9  False   False        False    False  False  False  False

In [ ]:
print("\nDataset info:")
print(df.info())

Dataset info:
<class 'pandas.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         351 non-null    str
 1   Author       351 non-null    str
 2   User Rating  351 non-null    float64
 3   Reviews      351 non-null    int64
 4   Price        351 non-null    int64
 5   Year         351 non-null    int64
 6   Genre        351 non-null    str
dtypes: float64(1), int64(3), str(3)
memory usage: 44.4 KB
None

In [ ]:
df.isnull().sum()

Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

In [ ]:
df.count()

Name           351
Author         351
User Rating    351
Reviews        351
Price          351
Year           351
Genre          351
dtype: int64

In [ ]:
df.count(),str()

(Name           351
 Author         351
 User Rating    351
 Reviews        351
 Price          351
 Year           351
 Genre          351
 dtype: int64,
 '')

In [ ]:
df.describe().count()

User Rating    8
Reviews        8
Price          8
Year           8
dtype: int64

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         351 non-null    str
 1   Author       351 non-null    str
 2   User Rating  351 non-null    float64
 3   Reviews      351 non-null    int64
 4   Price        351 non-null    int64
 5   Year         351 non-null    int64
 6   Genre        351 non-null    str
dtypes: float64(1), int64(3), str(3)
memory usage: 44.4 KB

In [ ]:
df.to_csv('Amazon_data')